### ISSUE TITLE
Max guests, description not being stored to database when editing a meal as a user or admin.

### ISSUE THREAD

**Issue by crw** [joyvuu-dave/comeals#6]
Fill fields:
![screen shot 2016-02-17 at 5 01 25 pm](https://cloud.githubusercontent.com/assets/57712/13130347/2ead43cc-d598-11e5-9732-5f6c41ef2290.png)

Click Update:
![screen shot 2016-02-17 at 5 01 33 pm](https://cloud.githubusercontent.com/assets/57712/13130353/3b5dbf98-d598-11e5-882b-6768fe9954cd.png)

See incorrect info:
![screen shot 2016-02-17 at 5 01 38 pm](https://cloud.githubusercontent.com/assets/57712/13130361/438a8c32-d598-11e5-9981-4a2b18a3ad16.png)

Info not returned when editing again:
![screen shot 2016-02-17 at 5 01 47 pm](https://cloud.githubusercontent.com/assets/57712/13130369/4d314d84-d598-11e5-8f54-19b1d03dc609.png)

**Comment by joyvuu-dave** [comment]
Fixed w/ 7d8038279d88b00efbbff888860e84a396db5a70. Deployed and tested.

**Comment by crw** [comment]
:+1:
